// src/components/NetworksView.svelte
<script>
  import { onMount } from "svelte";
  import { invoke } from "@tauri-apps/api/core";
  import { toast } from "svelte-sonner";
  import { renderComponent } from "../lib/renderComponent.js";
  import DataTable from "./DataTable.svelte";
  import CellRenderer from "./CellRenderer.svelte";

  let data = $state([]);
  let loading = $state(true);
  let loadingRows = $state(new Set());

  async function fetchNetworks() {
    try {
      data = await invoke("docker_networks");
    } catch (err) {
      console.error(err);
      toast.error("Failed to fetch networks");
    } finally {
      loading = false;
    }
  }

  function setRowLoading(key, isLoading) {
    const next = new Set(loadingRows);
    if (isLoading) next.add(key);
    else next.delete(key);
    loadingRows = next;
  }

  function handleAction(action, id, name) {
    if (action === 'remove') handleRemove(id, name);
  }

  async function handleRemove(id, name) {
    const key = `remove-${id}`;
    setRowLoading(key, true);
    try {
      await invoke("docker_remove_network", { id });
      toast.success(`Removed network: ${name}`);
      await fetchNetworks();
    } catch (err) {
      toast.error(`Remove failed: ${err}`);
    } finally {
      setRowLoading(key, false);
    }
  }

  const columns = $derived([
    { header: "ID", accessorKey: "ID" },
    { header: "Name", accessorKey: "Name" },
    { header: "Driver", accessorKey: "Driver" },
    { header: "Scope", accessorKey: "Scope" },
    { header: "IPv6", accessorKey: "IPv6" },
    { header: "Internal", accessorKey: "Internal" },
    {
      id: "actions",
      header: "Actions",
      cell: (info) => renderComponent(CellRenderer, {
        type: 'network_actions',
        row: info.row,
        loadingRows,
        onAction: handleAction
      })
    },
  ]);

  onMount(() => {
    fetchNetworks();
  });
</script>

<div class="p-5">
  <DataTable {data} {columns} {loading} emptyMessage="No networks found" />
</div>

// src/components/NetworksView.jsx
import { useEffect, useState, useCallback } from "react";
import { invoke } from "@tauri-apps/api/core";
import { toast } from "sonner";
import DataTable from "./DataTable";

const BUILTIN_NETWORKS = new Set(["bridge", "host", "none"]);

function NetworksView() {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [loadingRows, setLoadingRows] = useState(new Set());

  const fetchNetworks = useCallback(async () => {
    try {
      const result = await invoke("docker_networks");
      setData(result);
    } catch (err) {
      console.error(err);
      toast.error("Failed to fetch networks");
    } finally {
      setLoading(false);
    }
  }, []);

  const setRowLoading = (key, loading) =>
    setLoadingRows((prev) => {
      const next = new Set(prev);
      loading ? next.add(key) : next.delete(key);
      return next;
    });

  const handleRemove = async (id, name) => {
    const key = `remove-${id}`;
    setRowLoading(key, true);
    try {
      await invoke("docker_remove_network", { id });
      toast.success(`Removed network: ${name}`);
      await fetchNetworks();
    } catch (err) {
      toast.error(`Remove failed: ${err}`);
    } finally {
      setRowLoading(key, false);
    }
  };

  const columns = [
    { header: "ID", accessorKey: "ID" },
    { header: "Name", accessorKey: "Name" },
    { header: "Driver", accessorKey: "Driver" },
    { header: "Scope", accessorKey: "Scope" },
    { header: "IPv6", accessorKey: "IPv6" },
    { header: "Internal", accessorKey: "Internal" },
    {
      id: "actions",
      header: "Actions",
      cell: ({ row }) => {
        const id = row.original.ID;
        const name = row.original.Name;
        const isBuiltin = BUILTIN_NETWORKS.has(name);
        const removing = loadingRows.has(`remove-${id}`);
        return (
          <button
            disabled={isBuiltin || removing}
            onClick={() => handleRemove(id, name)}
            title={isBuiltin ? "Built-in network cannot be removed" : undefined}
            className="px-2.5 py-1 rounded-md text-xs font-medium bg-red-500 hover:bg-red-600 text-white transition-colors cursor-pointer disabled:opacity-60 disabled:cursor-not-allowed"
          >
            {removing ? "Removing…" : "Remove"}
          </button>
        );
      },
    },
  ];

  useEffect(() => {
    fetchNetworks();
  }, [fetchNetworks]);

  return (
    <div className="p-5">
      <DataTable data={data} columns={columns} loading={loading} emptyMessage="No networks found" />
    </div>
  );
}

export default NetworksView;
