// src/components/VolumesView.svelte
<script>
  import { onMount } from "svelte";
  import { invoke } from "@tauri-apps/api/core";
  import { toast } from "svelte-sonner";
  import { renderComponent } from "../lib/renderComponent.js";
  import DataTable from "./DataTable.svelte";
  import CellRenderer from "./CellRenderer.svelte";

  let data = $state([]);
  let loading = $state(true);
  let loadingRows = $state(new Set());

  async function fetchVolumes() {
    try {
      data = await invoke("docker_volumes");
    } catch (err) {
      console.error(err);
      toast.error("Failed to fetch volumes");
    } finally {
      loading = false;
    }
  }

  function setRowLoading(key, isLoading) {
    const next = new Set(loadingRows);
    if (isLoading) next.add(key);
    else next.delete(key);
    loadingRows = next;
  }

  function handleAction(action, name) {
    if (action === 'remove') handleRemove(name);
  }

  async function handleRemove(name) {
    const key = `remove-${name}`;
    setRowLoading(key, true);
    try {
      await invoke("docker_remove_volume", { name });
      toast.success(`Removed volume: ${name}`);
      await fetchVolumes();
    } catch (err) {
      toast.error(`Remove failed: ${err}`);
    } finally {
      setRowLoading(key, false);
    }
  }

  const columns = $derived([
    { header: "Name", accessorKey: "Name" },
    { header: "Driver", accessorKey: "Driver" },
    { header: "Scope", accessorKey: "Scope" },
    { header: "Mountpoint", accessorKey: "Mountpoint" },
    { header: "Labels", accessorKey: "Labels" },
    {
      id: "actions",
      header: "Actions",
      cell: (info) => renderComponent(CellRenderer, {
        type: 'volume_actions',
        row: info.row,
        loadingRows,
        onAction: handleAction
      })
    },
  ]);

  onMount(() => {
    fetchVolumes();
  });
</script>

<div class="p-5">
  <DataTable {data} {columns} {loading} emptyMessage="No volumes found" />
</div>

// src/components/VolumesView.jsx
import { useEffect, useState, useCallback } from "react";
import { invoke } from "@tauri-apps/api/core";
import { toast } from "sonner";
import DataTable from "./DataTable";

function VolumesView() {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [loadingRows, setLoadingRows] = useState(new Set());

  const fetchVolumes = useCallback(async () => {
    try {
      const result = await invoke("docker_volumes");
      setData(result);
    } catch (err) {
      console.error(err);
      toast.error("Failed to fetch volumes");
    } finally {
      setLoading(false);
    }
  }, []);

  const setRowLoading = (key, loading) =>
    setLoadingRows((prev) => {
      const next = new Set(prev);
      loading ? next.add(key) : next.delete(key);
      return next;
    });

  const handleRemove = async (name) => {
    const key = `remove-${name}`;
    setRowLoading(key, true);
    try {
      await invoke("docker_remove_volume", { name });
      toast.success(`Removed volume: ${name}`);
      await fetchVolumes();
    } catch (err) {
      toast.error(`Remove failed: ${err}`);
    } finally {
      setRowLoading(key, false);
    }
  };

  const columns = [
    { header: "Name", accessorKey: "Name" },
    { header: "Driver", accessorKey: "Driver" },
    { header: "Scope", accessorKey: "Scope" },
    { header: "Mountpoint", accessorKey: "Mountpoint" },
    { header: "Labels", accessorKey: "Labels" },
    {
      id: "actions",
      header: "Actions",
      cell: ({ row }) => {
        const name = row.original.Name;
        const removing = loadingRows.has(`remove-${name}`);
        return (
          <button
            disabled={removing}
            onClick={() => handleRemove(name)}
            className="px-2.5 py-1 rounded-md text-xs font-medium bg-red-500 hover:bg-red-600 text-white transition-colors cursor-pointer disabled:opacity-60 disabled:cursor-not-allowed"
          >
            {removing ? "Removing…" : "Remove"}
          </button>
        );
      },
    },
  ];

  useEffect(() => {
    fetchVolumes();
  }, [fetchVolumes]);

  return (
    <div className="p-5">
      <DataTable data={data} columns={columns} loading={loading} emptyMessage="No volumes found" />
    </div>
  );
}

export default VolumesView;
